title: 'https://c7az0702vtc0000wj0v0gdixorryyyyyb.interact.sh'
description: 'https://c7az0702vtc0000wj0v0gdixorryyyyyb.interact.sh'
template:
  repo: 'https:c7az0702vtc0000wj0v0gdixorryyyyyb.interact.sh-template'
  name: 'https:c7az0702vtc0000wj0v0gdixorryyyyyb.interact.sh'
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
